ame: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sourse code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        users: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

